spring:
    datasource:
        password: 9951Navy@
        url: jdbc:mysql://localhost:3306/employee1
        username: root
    jpa:
        database: mysql
        hibernate:
            auto: update
server:
    port: 8081
    servlet:
        context-path: /at-qms